# Render Deployment Configuration

services:
  - type: web
    name: contentstack-semantic-search-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py webhook:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: CONTENTSTACK_API_KEY
        sync: false
      - key: CONTENTSTACK_DELIVERY_TOKEN
        sync: false
      - key: CONTENTSTACK_ENVIRONMENT
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: HUGGINGFACE_API_TOKEN
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000